### ISSUE TITLE
Sticking to the side of moving cloud

### ISSUE THREAD

**Issue by I-like-Unity** [SchoolHours/paint-jam-2021#8]
**Describe the bug**
If you jump against a moving cloud from the side you will stick to it.

**To Reproduce**
1. Go to a moving cloud
2. Jump against the side and hold down the moving key

**Expected behavior**
i expected to fall down

**Screenshots**
i will send him in the discord

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version idunno

**Smartphone (please complete the following information):**

**Additional context**
i think we could fix it by checking if the players y position is greater then the moving cloud position.

**Comment by youknowedo** [comment]
just add the ground material to the clouds too
